source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.2'

gem 'rails', '~> 7.1.0'
gem 'sqlite3', '~> 1.4'
gem 'puma', '~> 6.0'
gem 'bootsnap', require: false
gem 'bcrypt', '~> 3.1.7'
gem 'jwt'
gem 'rack-cors'

group :development, :test do
  gem 'debug', platforms: %i[ mri mingw x64_mingw ]
  gem 'rspec-rails'
  gem 'cucumber-rails', require: false
  gem 'database_cleaner'
end

group :development do
  gem 'web-console'
end

gem 'tzinfo-data', platforms: %i[ mingw mswin x64_mingw jruby ]
